In [7]:
# Dependencies and Setup
import pandas as pd
import numpy as np

# File Load (CSV)
files_to_load= os.path.join("DroughtData_2010_2019.csv")

# Read (CSV)
data= pd.read_csv(files_to_load)
df= pd.DataFrame(data)

In [14]:
df = df.loc[:, ~df.columns.str.contains('^Unnamed')]
df

,Date,StateAbbreviation,None,D0,D1,D2,D3,D4,ValidStart,ValidEnd,StatisticFormatID
0,2019,AK,"516,396.68","66,184.79","29,277.83","11,664.38","5,101.16",0,10/8/2019,10/14/2019,1
1,2019,AK,"516,396.68","66,184.79","29,277.83","11,664.38","5,101.16",0,10/1/2019,10/7/2019,1
2,2019,AK,"479,134.69","103,446.79","60,337.27","15,413.01","5,101.16",0,9/24/2019,9/30/2019,1
3,2019,AK,"443,823.87","138,757.60","69,240.83","34,192.52","8,747.25",0,9/17/2019,9/23/2019,1
4,2019,AK,"413,374.73","169,206.74","103,956.37","39,419.36","8,747.25",0,9/10/2019,9/16/2019,1
5,2019,AK,"402,551.51","180,029.97","103,956.37","39,419.36","8,747.25",0,9/3/2019,9/9/2019,1
6,2019,AK,"388,413.49","194,167.99","103,956.37","39,419.36","8,747.25",0,8/27/2019,9/2/2019,1
7,2019,AK,"388,413.49","194,167.99","65,217.85","26,707.89","7,680.55",0,8/20/2019,8/26/2019,1
8,2019,AK,"404,160.77","178,420.70","56,082.94","21,944.64","5,101.16",0,8/13/2019,8/19/2019,1
9,2019,AK,"296,295.86","286,285.61","67,829.87","11,664.38","5,101.16",0,8/6/2019,8/12/2019,1
10,2019,AK,"176,941.52","405,639.96","142,560.81","33,730.35","5,101.16",0,7/30/2019,8/5/2019,1
11,2019,AK,"176,941.52","405,639.96","142,560.81","33,730.35","5,101.16",0,7/23/2019,7/29/2019,1
12,2019,AK,"178,779.89","403,801.59","140,398.17","11,664.38","5,101.16",0,7/16/2019,7/22/2019,1
13,2019,AK,"219,361.75","363,219.72","30,551.98","9,600.84","5,101.16",0,7/9/2019,7/15/2019,1
14,2019,AK,"510,602.43","71,979.04","16,186.75","9,600.84","5,101.16",0,7/2/2019,7/8/2019,1
15,2019,AK,"510,602.43","71,979.04","16,186.75","9,600.84","5,101.16",0,6/25/2019,7/1/2019,1
16,2019,AK,"510,602.43","71,979.04","16,186.75","9,600.84","5,101.16",0,6/18/2019,6/24/2019,1
17,2019,AK,"548,627.60","33,953.88","16,186.75","9,600.84","5,101.16",0,6/11/2019,6/17/2019,1
18,2019,AK,"548,627.60","33,953.88","16,186.75","9,600.84","5,101.16",0,6/4/2019,6/10/2019,1
19,2019,AK,"548,627.60","33,953.88","16,186.75","9,600.84","5,101.16",0,5/28/2019,6/3/2019,1
20,2019,AK,"548,627.60","33,953.88","16,186.75","9,600.84","5,101.16",0,5/21/2019,5/27/2019,1
21,2019,AK,"548,627.60","33,953.88","12,873.67","5,402.70",0,0,5/14/2019,5/20/2019,1
22,2019,AK,"548,627.60","33,953.88","12,873.67","5,402.70",0,0,5/7/2019,5/13/2019,1
23,2019,AK,"548,627.64","33,953.83","21,788.68","9,856.40",0,0,4/30/2019,5/6/2019,1
24,2019,AK,"548,627.60","33,953.88","21,788.75","11,224.77",0,0,4/23/2019,4/29/2019,1
25,2019,AK,"548,627.60","33,953.88","21,788.75","11,224.77",0,0,4/16/2019,4/22/2019,1
26,2019,AK,"548,627.60","33,953.88","21,788.75","11,224.77",0,0,4/9/2019,4/15/2019,1
27,2019,AK,"548,627.60","33,953.88","21,788.75","11,224.77",0,0,4/2/2019,4/8/2019,1
28,2019,AK,"548,627.60","33,953.88","21,788.75","11,224.77",0,0,3/26/2019,4/1/2019,1
29,2019,AK,"548,627.60","33,953.88","21,788.75","11,224.77",0,0,3/19/2019,3/25/2019,1
...,...,...,...,...,...,...,...,...,...,...,...
26542,2010,WY,"67,451.72","30,346.90","7,248.15",0,0,0,7/20/2010,7/26/2010,1
26543,2010,WY,"67,451.72","30,346.90","7,248.15",0,0,0,7/13/2010,7/19/2010,1
26544,2010,WY,"67,451.72","30,346.90","7,248.15",0,0,0,7/6/2010,7/12/2010,1
26545,2010,WY,"58,573.72","39,224.90","27,151.80","6,259.28",0,0,6/29/2010,7/5/2010,1
26546,2010,WY,"58,573.72","39,224.90","27,151.80","6,259.28",0,0,6/22/2010,6/28/2010,1
26547,2010,WY,"58,573.72","39,224.90","29,078.87","8,333.34",0,0,6/15/2010,6/21/2010,1
26548,2010,WY,"58,349.03","39,449.59","29,122.64","8,333.34",0,0,6/8/2010,6/14/2010,1
26549,2010,WY,"58,623.61","39,175.01","28,787.46","12,250.85",0,0,6/1/2010,6/7/2010,1
26550,2010,WY,"58,460.24","39,338.38","28,904.63","12,250.85",0,0,5/25/2010,5/31/2010,1
26551,2010,WY,"55,346.29","42,452.33","30,969.20","15,126.67",0,0,5/18/2010,5/24/2010,1
26552,2010,WY,"38,517.06","59,281.56","34,138.88","15,313.37",0,0,5/11/2010,5/17/2010,1
26553,2010,WY,"27,642.18","70,156.44","35,960.78","15,313.37",0,0,5/4/2010,5/10/2010,1
26554,2010,WY,"27,642.18","70,156.44","35,960.78","15,313.37",0,0,4/27/2010,5/3/2010,1
26555,2010,WY,"27,642.18","70,156.44","35,944.86","15,322.23",0,0,4/20/2010,4/26/2010,1
26556,2010,WY,"26,417.08","71,381.54","35,564.84","13,636.76",0,0,4/13/2010,4/19/2010,1
26557,2010,WY,"21,831.74","75,966.88","37,621.74","13,636.76",0,0,4/6/2010,4/12/2010,1
26558,2010,WY,"21,831.74","75,966.88","37,621.74","13,636.76",0,0,3/30/2010,4/5/2010,1
26559,2010,WY,"25,187.28","72,611.34","37,621.74","13,636.76",0,0,3/23/2010,3/29/2010,1
26560,2010,WY,"25,187.28","72,611.34","37,621.74","13,636.76",0,0,3/16/2010,3/22/2010,1
26561,2010,WY,"25,155.99","72,642.62","37,621.74","7,660.53",0,0,3/9/2010,3/15/2010,1
26562,2010,WY,"25,155.99","72,642.62","28,447.52",0,0,0,3/2/2010,3/8/2010,1
26563,2010,WY,"25,155.99","72,642.62","28,447.52",0,0,0,2/23/2010,3/1/2010,1
26564,2010,WY,"25,325.95","72,472.67","22,678.63",0,0,0,2/16/2010,2/22/2010,1
26565,2010,WY,"51,189.74","46,608.88","9,270.76",0,0,0,2/9/2010,2/15/2010,1
26566,2010,WY,"51,189.74","46,608.88","9,270.76",0,0,0,2/2/2010,2/8/2010,1
26567,2010,WY,"62,607.96","35,190.66","9,662.02",0,0,0,1/26/2010,2/1/2010,1
26568,2010,WY,"63,034.87","34,763.75","7,564.96",0,0,0,1/19/2010,1/25/2010,1
26569,2010,WY,"63,960.33","33,838.29",899.19,0,0,0,1/12/2010,1/18/2010,1
26570,2010,WY,"77,514.35","20,284.27",874.1,0,0,0,1/5/2010,1/11/2010,1
26571,2009,WY,"84,858.01","12,940.61",0,0,0,0,12/29/2009,1/4/2010,1

In [17]:
groupby= df.groupby(["Date","StateAbbreviation","None","D0","D1","D2","D3","D4"]).mean()
reset= groupby.reset_index()
reset

,Date,StateAbbreviation,None,D0,D1,D2,D3,D4,StatisticFormatID
0,2009,AK,"417,130.28","165,451.20",0,0,0,0,1
1,2009,AL,"51,613.84",0,0,0,0,0,1
2,2009,AR,"53,162.75",0,0,0,0,0,1
3,2009,AZ,0,"114,034.82","110,881.68","81,172.50","5,775.17",0,1
4,2009,CA,"10,380.50","147,767.56","114,122.22","14,618.26",0,0,1
5,2009,CO,"72,088.76","32,056.90","7,835.34",0,0,0,1
6,2009,CT,"4,978.77",0,0,0,0,0,1
7,2009,DC,60.21,0,0,0,0,0,1
8,2009,DE,"2,049.97",0,0,0,0,0,1
9,2009,FL,"54,753.76","1,760.96",0,0,0,0,1
10,2009,GA,"58,777.25",0,0,0,0,0,1
11,2009,HI,"1,985.51","4,486.57","3,458.78","1,864.60",329.72,0,1
12,2009,IA,"56,311.50",0,0,0,0,0,1
13,2009,ID,"45,476.63","38,091.81",0,0,0,0,1
14,2009,IL,"56,382.55",0,0,0,0,0,1
15,2009,IN,"36,199.11",0,0,0,0,0,1
16,2009,KS,"82,287.40",0,0,0,0,0,1
17,2009,KY,"40,357.37",0,0,0,0,0,1
18,2009,LA,"46,909.56",0,0,0,0,0,1
19,2009,MA,"8,137.17",0,0,0,0,0,1
20,2009,MD,"9,805.81",0,0,0,0,0,1
21,2009,ME,"32,469.86",0,0,0,0,0,1
22,2009,MI,"51,010.26","7,147.30","2,333.31",0,0,0,1
23,2009,MN,"58,982.99","25,398.19","1,299.34",0,0,0,1
24,2009,MO,"69,718.06",0,0,0,0,0,1
25,2009,MS,"47,714.28",0,0,0,0,0,1
26,2009,MT,"77,337.26","69,751.06",0,0,0,0,1
27,2009,NC,"49,268.58",0,0,0,0,0,1
28,2009,ND,"62,991.15","7,715.14",0,0,0,0,1
29,2009,NE,"77,300.00",0,0,0,0,0,1
...,...,...,...,...,...,...,...,...,...
15318,2019,WV,99.33,"24,105.34","9,752.92",0,0,0,1
15319,2019,WY,"39,629.31","58,169.31","16,385.61",0,0,0,1
15320,2019,WY,"41,679.21","56,119.41","16,385.61",0,0,0,1
15321,2019,WY,"41,679.21","56,119.41","2,837.83",0,0,0,1
15322,2019,WY,"41,679.21","56,119.41","6,835.70",0,0,0,1
15323,2019,WY,"42,338.26","55,460.36","2,832.92",0,0,0,1
15324,2019,WY,"45,485.84","52,312.78","16,385.61",0,0,0,1
15325,2019,WY,"47,055.84","50,742.78","16,357.98","3,194.04",0,0,1
15326,2019,WY,"47,055.84","50,742.78","16,357.98",317.07,0,0,1
15327,2019,WY,"47,055.84","50,742.78","16,385.61",317.07,0,0,1
15328,2019,WY,"57,055.60","40,743.02","13,115.63","3,194.04",0,0,1
15329,2019,WY,"61,780.11","36,018.51","13,115.63","3,194.04",0,0,1
15330,2019,WY,"66,995.80","30,802.82","4,734.77",0,0,0,1
15331,2019,WY,"67,557.52","30,241.10","2,832.92",0,0,0,1
15332,2019,WY,"72,391.73","25,406.89","2,832.92",0,0,0,1
15333,2019,WY,"75,566.66","22,231.96",0,0,0,0,1
15334,2019,WY,"76,597.79","21,200.83","3,920.01",0,0,0,1
15335,2019,WY,"77,235.70","20,562.92",0,0,0,0,1
15336,2019,WY,"77,464.49","20,334.13","1,982.19",0,0,0,1
15337,2019,WY,"82,715.09","15,083.53","1,711.15",0,0,0,1
15338,2019,WY,"83,381.44","14,417.18","1,594.37",0,0,0,1
15339,2019,WY,"83,601.16","14,197.46",0,0,0,0,1
15340,2019,WY,"85,487.18","12,311.44","1,711.15",0,0,0,1
15341,2019,WY,"89,011.02","8,787.60",0,0,0,0,1
15342,2019,WY,"89,014.29","8,784.33",0,0,0,0,1
15343,2019,WY,"89,821.76","7,976.86",0,0,0,0,1
15344,2019,WY,"93,315.05","4,483.57",0,0,0,0,1
15345,2019,WY,"94,126.55","3,672.07",0,0,0,0,1
15346,2019,WY,"97,209.43",589.19,0,0,0,0,1
15347,2019,WY,"97,798.62",0,0,0,0,0,1

In [18]:
reset.to_csv(r'CleanDroughtData_2010-2019.csv')