In [5]:
# Dependencies and Setup
import matplotlib.pyplot as plt
import pandas as pd
import numpy as np
import requests
import time
import os
from datetime import datetime


# File Load (CSV)
files_to_load= os.path.join("CornPRICESRECEIVED_DollarperBU_AllStates_2010-2019.csv")

# Read (CSV)
data= pd.read_csv(files_to_load)
data.head()

,Program,Year,Period,Geo Level,State,State ANSI,Commodity,Data Item,Domain,Domain Category,Values
0,SURVEY,2019,JAN,STATE,ALABAMA,1,CORN,"CORN, GRAIN - PRICE RECEIVED, MEASURED IN $ / BU",TOTAL,NOT SPECIFIED,3.99
1,SURVEY,2019,JAN,STATE,ALASKA,2,CORN,"CORN, GRAIN - PRICE RECEIVED, MEASURED IN $ / BU",TOTAL,NOT SPECIFIED,0.00
2,SURVEY,2019,JAN,STATE,ARIZONA,4,CORN,"CORN, GRAIN - PRICE RECEIVED, MEASURED IN $ / BU",TOTAL,NOT SPECIFIED,0.00
3,SURVEY,2019,JAN,STATE,ARKANSAS,5,CORN,"CORN, GRAIN - PRICE RECEIVED, MEASURED IN $ / BU",TOTAL,NOT SPECIFIED,3.83
4,SURVEY,2019,JAN,STATE,CALIFORNIA,6,CORN,"CORN, GRAIN - PRICE RECEIVED, MEASURED IN $ / BU",TOTAL,NOT SPECIFIED,0.00

In [46]:
yeargroup = data.groupby(["Year","State"]).mean()
yeargroup.reset_index()

     Year           State  State ANSI    Values
0    2010        COLORADO           8  3.793333
1    2010        ILLINOIS          17  3.851667
2    2010         INDIANA          18  3.983333
3    2010            IOWA          19  3.858333
4    2010          KANSAS          20  3.828333
5    2010        KENTUCKY          21  4.073333
6    2010        MICHIGAN          26  3.857500
7    2010       MINNESOTA          27  3.635000
8    2010        MISSOURI          29  3.939167
9    2010        NEBRASKA          31  3.832500
10   2010  NORTH CAROLINA          37  4.514167
11   2010    NORTH DAKOTA          38  3.446667
12   2010            OHIO          39  3.919167
13   2010    PENNSYLVANIA          42  4.420000
14   2010    SOUTH DAKOTA          46  3.485000
15   2010       TENNESSEE          47  4.120833
16   2010           TEXAS          48  4.096667
17   2010       WISCONSIN          55  3.738333
18   2011        COLORADO           8  6.041667
19   2011        ILLINOIS          17  6.141667
20   2011         INDIANA          18  6.240833
21   2011            IOWA          19  5.964167
22   2011          KANSAS          20  6.331667
23   2011        KENTUCKY          21  6.236667
24   2011        MICHIGAN          26  6.220000
25   2011       MINNESOTA          27  5.635000
26   2011        MISSOURI          29  6.217500
27   2011        NEBRASKA          31  5.916667
28   2011  NORTH CAROLINA          37  7.033333
29   2011    NORTH DAKOTA          38  5.646667
..    ...             ...         ...       ...
278  2019   MASSACHUSETTS          25  0.000000
279  2019        MICHIGAN          26  3.920000
280  2019       MINNESOTA          27  3.555000
281  2019     MISSISSIPPI          28  0.986250
282  2019        MISSOURI          29  3.850000
283  2019         MONTANA          30  0.000000
284  2019        NEBRASKA          31  3.701250
285  2019          NEVADA          32  0.000000
286  2019   NEW HAMPSHIRE          33  0.000000
287  2019      NEW JERSEY          34  0.000000
288  2019      NEW MEXICO          35  0.000000
289  2019        NEW YORK          36  4.263750
290  2019  NORTH CAROLINA          37  4.547500
291  2019    NORTH DAKOTA          38  3.400000
292  2019            OHIO          39  3.970000
293  2019        OKLAHOMA          40  4.012500
294  2019          OREGON          41  0.000000
295  2019    PENNSYLVANIA          42  4.341250
296  2019    RHODE ISLAND          44  0.000000
297  2019  SOUTH CAROLINA          45  0.000000
298  2019    SOUTH DAKOTA          46  3.538750
299  2019       TENNESSEE          47  3.961250
300  2019           TEXAS          48  4.320000
301  2019            UTAH          49  0.000000
302  2019         VERMONT          50  0.000000
303  2019        VIRGINIA          51  3.887500
304  2019      WASHINGTON          53  0.543750
305  2019   WEST VIRGINIA          54  0.000000
306  2019       WISCONSIN          55  3.643750
307  2019         WYOMING          56  0.000000

[308 rows x 4 columns]

In [49]:
yeargroup.to_csv(r'pandas_clean_PricesReceived.csv')